/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/videos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Videos */
        get: operations["list_videos_api_v1_videos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/videos/counts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Counts */
        get: operations["counts_api_v1_videos_counts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/videos/from-links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create From Links */
        post: operations["create_from_links_api_v1_videos_from_links_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/videos/{video_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Video */
        get: operations["get_video_api_v1_videos__video_id__get"];
        put?: never;
        post?: never;
        /** Delete Video */
        delete: operations["delete_video_api_v1_videos__video_id__delete"];
        options?: never;
        head?: never;
        /** Update Video */
        patch: operations["update_video_api_v1_videos__video_id__patch"];
        trace?: never;
    };
    "/api/v1/videos/{video_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry */
        post: operations["retry_api_v1_videos__video_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/videos/{video_id}/translate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Translate
         * @description Chạy nửa sau pipeline với model AI người dùng vừa chọn.
         *
         *     Pipeline dừng ở trạng thái ``review`` sau bước nhận dạng để người dùng
         *     chọn model (lúc đó đã biết video có bao nhiêu câu thoại). Endpoint này
         *     khởi động lại — luật số 1 CLAUDE.md: dịch chạy hàng phút nên luôn qua
         *     Celery, endpoint trả 202 chứ không chờ.
         */
        post: operations["translate_api_v1_videos__video_id__translate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/videos/{video_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve */
        post: operations["approve_api_v1_videos__video_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/videos/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bulk */
        post: operations["bulk_api_v1_videos_bulk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/videos/{video_id}/subtitles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Subtitles */
        get: operations["subtitles_api_v1_videos__video_id__subtitles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/videos/{video_id}/job-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Runs */
        get: operations["job_runs_api_v1_videos__video_id__job_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/videos/{video_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download File
         * @description Tải bản render cuối cùng.
         */
        get: operations["download_file_api_v1_videos__video_id__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Presets */
        get: operations["list_presets_api_v1_presets_get"];
        put?: never;
        /** Create Preset */
        post: operations["create_preset_api_v1_presets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/presets/{preset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Preset */
        patch: operations["update_preset_api_v1_presets__preset_id__patch"];
        trace?: never;
    };
    "/api/v1/source-channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Channels */
        get: operations["list_channels_api_v1_source_channels_get"];
        put?: never;
        /** Create Channel */
        post: operations["create_channel_api_v1_source_channels_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/source-channels/{channel_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Channel */
        delete: operations["delete_channel_api_v1_source_channels__channel_id__delete"];
        options?: never;
        head?: never;
        /** Update Channel */
        patch: operations["update_channel_api_v1_source_channels__channel_id__patch"];
        trace?: never;
    };
    "/api/v1/source-channels/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve Channel
         * @description Phân tích URL kênh — CHỈ đọc chuỗi URL, TUYỆT ĐỐI KHÔNG gọi mạng.
         *
         *     Việc lấy tên hiển thị / số follower / video mẫu thật là việc của task
         *     Celery quét kênh, chạy ở chặng sau. Ở đây luôn trả ``needs_scan=True``.
         */
        post: operations["resolve_channel_api_v1_source_channels_resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform-limits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Platform Limits */
        get: operations["list_platform_limits_api_v1_platform_limits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform-limits/{platform}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Platform Limit */
        patch: operations["update_platform_limit_api_v1_platform_limits__platform__patch"];
        trace?: never;
    };
    "/api/v1/videos/{video_id}/render": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Render Video
         * @description Kích hoạt render nhiều bản (một bản mỗi nền tảng đích). Luật số 10
         *     CLAUDE.md: render chạy hàng phút -> luôn qua Celery, endpoint không chờ.
         */
        post: operations["render_video_api_v1_videos__video_id__render_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/videos/{video_id}/variants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Variants */
        get: operations["list_variants_api_v1_videos__video_id__variants_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/variants/{variant_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Variant File
         * @description Tải file của một render variant.
         */
        get: operations["download_variant_file_api_v1_variants__variant_id__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/llm/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Llm Models
         * @description Model của khoá hiện tại, chia nhóm dịch và giọng nói.
         *
         *     Có chạm mạng ngoài nhưng KHÔNG qua Celery (xem lý do ở
         *     ``services/llm_model_service.py``): một lượt GET nhẹ, chặn bằng hạn chờ
         *     ngắn và cache 5 phút. Hỏng thì trả lỗi rõ ràng chứ không bao giờ trả danh
         *     sách rỗng kèm 200.
         */
        get: operations["list_llm_models_api_v1_llm_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/llm/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Llm Usage */
        get: operations["get_llm_usage_api_v1_llm_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BulkAction */
        BulkAction: {
            /** Ids */
            ids: string[];
            /**
             * Action
             * @enum {string}
             */
            action: "approve" | "delete" | "retry" | "apply_preset" | "assign_channels";
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
        };
        /**
         * BulkResult
         * @description Kết quả ``POST /videos/bulk``.
         *
         *     Trước đây endpoint trả ``dict`` trần nên OpenAPI chỉ mô tả được "một object
         *     bất kỳ", và frontend phải gõ tay lại interface.
         *
         *     ``skipped`` LUÔN kèm lý do và giao diện phải hiển thị — video bị bỏ qua âm
         *     thầm là cách nhanh nhất để người dùng tưởng đã duyệt xong cả lô.
         */
        BulkResult: {
            /** Affected */
            affected: number;
            /** Action */
            action: string;
            /** Skipped */
            skipped: components["schemas"]["BulkSkip"][];
        };
        /** BulkSkip */
        BulkSkip: {
            /** Id */
            id: string;
            /** Reason */
            reason: string;
        };
        /** CreateFromLinks */
        CreateFromLinks: {
            /** Urls */
            urls: string[];
            /** Process Config */
            process_config?: {
                [key: string]: unknown;
            };
            /**
             * Autostart
             * @default true
             */
            autostart: boolean;
        };
        /** CreateFromLinksResult */
        CreateFromLinksResult: {
            /** Created */
            created: number;
            /** Skipped Duplicate */
            skipped_duplicate: number;
            /** Invalid */
            invalid?: string[];
            /** Video Ids */
            video_ids?: string[];
            /** Duplicate Ids */
            duplicate_ids?: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobRunOut */
        JobRunOut: {
            step: components["schemas"]["PipelineStep"];
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "success" | "failed";
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at?: string | null;
            /** Duration Sec */
            duration_sec?: number | null;
            /** Log */
            log?: string | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
        };
        /**
         * LicenseStatus
         * @description Tình trạng quyền sử dụng của kênh nguồn.
         *
         *     ``UNKNOWN`` là mặc định và **chặn luồng tự động** — đây là chốt an toàn
         *     pháp lý, không được bỏ qua vì tiện.
         * @enum {string}
         */
        LicenseStatus: "unknown" | "permitted" | "licensed" | "open" | "own";
        /**
         * LlmModelsOut
         * @description Model dùng được với khoá hiện tại, đã lọc theo mục đích.
         *
         *     Chia sẵn hai nhóm thay vì trả danh sách phẳng kèm nhãn: ô chọn "AI dịch" và
         *     ô chọn "giọng đọc" là hai chỗ khác nhau, và nhóm sai thì người dùng chọn
         *     phải model chỉ có 10 lượt/ngày.
         */
        LlmModelsOut: {
            /** Translate */
            translate: string[];
            /** Tts */
            tts: string[];
            /**
             * Default
             * @default
             */
            default: string;
        };
        /** LlmUsageOut */
        LlmUsageOut: {
            /**
             * Requests Last Min
             * @description Số lượt gọi LLM trong 60 giây gần nhất.
             */
            requests_last_min: number;
            /**
             * Requests Last Day
             * @description Số lượt gọi LLM trong 24 giờ gần nhất.
             */
            requests_last_day: number;
            /**
             * Tokens Last Day
             * @description Tổng token LLM trong 24 giờ gần nhất.
             */
            tokens_last_day: number;
            /**
             * Cost Usd This Month
             * @description Tiền LLM đã tiêu từ đầu tháng (UTC).
             */
            cost_usd_this_month: number;
            /**
             * Max Requests Per Min
             * @description 0 = KHÔNG giới hạn (chưa khai trần), không phải cấm gọi.
             */
            max_requests_per_min: number;
            /**
             * Max Requests Per Day
             * @description 0 = KHÔNG giới hạn (chưa khai trần), không phải cấm gọi.
             */
            max_requests_per_day: number;
            /**
             * Monthly Budget Usd
             * @description 0 = KHÔNG giới hạn (chưa khai trần), không phải cấm gọi.
             */
            monthly_budget_usd: number;
        };
        /** Page[VideoOut] */
        Page_VideoOut_: {
            /** Items */
            items: components["schemas"]["VideoOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Limit */
            limit: number;
        };
        /**
         * PipelineStep
         * @enum {string}
         */
        PipelineStep: "download" | "probe" | "transcribe" | "translate" | "format_sub" | "detect" | "inpaint" | "shortform" | "tts" | "render" | "qc" | "upload";
        /**
         * Platform
         * @description Nền tảng đăng (Việt Nam) — tập trung vào video ngắn.
         * @enum {string}
         */
        Platform: "tiktok" | "youtube" | "facebook" | "instagram" | "zalo";
        /** PlatformLimitOut */
        PlatformLimitOut: {
            /** Platform */
            platform: string;
            /**
             * Max Duration Sec
             * @description Số giây tối đa. 0 = KHÔNG giới hạn thời lượng (không phải dữ liệu thiếu).
             */
            max_duration_sec: number;
            /** Max Title Len */
            max_title_len: number;
            /** Max Desc Len */
            max_desc_len: number;
            /** Max Hashtags */
            max_hashtags: number;
            /** Safe Daily Posts */
            safe_daily_posts: number;
            /** Aspect Ratios */
            aspect_ratios: string[];
            safe_area: components["schemas"]["SafeArea"];
            /** Notes */
            notes: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** PlatformLimitUpdate */
        PlatformLimitUpdate: {
            /**
             * Max Duration Sec
             * @description Số giây tối đa. 0 = KHÔNG giới hạn thời lượng (không phải dữ liệu thiếu).
             */
            max_duration_sec?: number | null;
            /** Max Title Len */
            max_title_len?: number | null;
            /** Max Desc Len */
            max_desc_len?: number | null;
            /** Max Hashtags */
            max_hashtags?: number | null;
            /** Safe Daily Posts */
            safe_daily_posts?: number | null;
            /** Aspect Ratios */
            aspect_ratios?: string[] | null;
            safe_area?: components["schemas"]["SafeArea"] | null;
            /** Notes */
            notes?: string | null;
        };
        /** PresetCreate */
        PresetCreate: {
            kind: components["schemas"]["PresetKind"];
            /** Name */
            name: string;
            /** Config */
            config?: {
                [key: string]: unknown;
            };
            /**
             * Is Default
             * @default false
             */
            is_default: boolean;
        };
        /**
         * PresetKind
         * @description Loại preset cấu hình chỉnh được từ giao diện — đổi preset không cần sửa code.
         * @enum {string}
         */
        PresetKind: "filter" | "process" | "antidup" | "subtitle";
        /** PresetOut */
        PresetOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Name */
            name: string;
            /** Config */
            config?: {
                [key: string]: unknown;
            };
            /** Is Default */
            is_default: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** PresetUpdate */
        PresetUpdate: {
            /** Name */
            name?: string | null;
            /** Config */
            config?: {
                [key: string]: unknown;
            } | null;
            /** Is Default */
            is_default?: boolean | null;
        };
        /**
         * RenderRequest
         * @description Body của ``POST /videos/{id}/render``.
         *
         *     ``target_platforms`` bắt buộc có ít nhất một phần tử (danh sách rỗng ->
         *     422 tự động nhờ ``min_length``) và mỗi phần tử phải nằm trong enum
         *     ``Platform`` (nền tảng lạ -> 422 tự động nhờ kiểu ``list[Platform]``).
         *     Việc kiểm thêm mỗi nền tảng có dòng ``platform_limits`` tương ứng hay
         *     không nằm ở tầng service, vì đó là logic nghiệp vụ cần đọc DB.
         */
        RenderRequest: {
            /** Target Platforms */
            target_platforms: components["schemas"]["Platform"][];
            /** Preset Overrides */
            preset_overrides?: {
                [key: string]: unknown;
            };
        };
        /** RenderVariantOut */
        RenderVariantOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Video Id
             * Format: uuid
             */
            video_id: string;
            /** Target Platform */
            target_platform: string;
            /** Part Index */
            part_index: number;
            /** Part Total */
            part_total: number;
            /** Out Path */
            out_path?: string | null;
            /** Duration Sec */
            duration_sec?: number | null;
            /** Width */
            width?: number | null;
            /** Height */
            height?: number | null;
            /** File Size */
            file_size?: number | null;
            /** Config Snapshot */
            config_snapshot?: {
                [key: string]: unknown;
            };
            /** Qc Passed */
            qc_passed?: boolean | null;
            /** Qc Report */
            qc_report?: {
                [key: string]: unknown;
            } | null;
        };
        /** ResolveChannelRequest */
        ResolveChannelRequest: {
            /** Url */
            url: string;
        };
        /**
         * ResolveChannelResult
         * @description Kết quả phân tích URL kênh — CHỈ từ URL, KHÔNG gọi mạng.
         *
         *     ``display_name``/``follower_count``/``sample_videos`` luôn rỗng/null ở M2:
         *     lấy metadata thật là việc của task Celery quét kênh, làm ở chặng sau.
         */
        ResolveChannelResult: {
            platform: components["schemas"]["SourcePlatform"];
            /** External Id */
            external_id: string;
            /** Handle */
            handle: string | null;
            /** Url */
            url: string;
            /** Display Name */
            display_name?: string | null;
            /** Follower Count */
            follower_count?: number | null;
            /** Sample Videos */
            sample_videos?: string[];
            /**
             * Needs Scan
             * @default true
             */
            needs_scan: boolean;
        };
        /**
         * SafeArea
         * @description Vùng bị giao diện nền tảng che, theo PHẦN TRĂM 0–1 (luật số 2 CLAUDE.md).
         *
         *     Khai thành model chứ không phải ``dict[str, float]``: dict cho ra
         *     ``additionalProperties`` trong OpenAPI, mất sạch tên bốn cạnh, nên frontend
         *     phải gõ tay lại interface — đúng thứ luật số 7 cấm.
         */
        SafeArea: {
            /** Top */
            top: number;
            /** Bottom */
            bottom: number;
            /** Left */
            left: number;
            /** Right */
            right: number;
        };
        /** SourceChannelCreate */
        SourceChannelCreate: {
            platform: components["schemas"]["SourcePlatform"];
            /** External Id */
            external_id: string;
            /** Url */
            url: string;
            /** Handle */
            handle?: string | null;
            /** Display Name */
            display_name?: string | null;
            /**
             * Scan Interval Min
             * @default 60
             */
            scan_interval_min: number;
            /** Filter Preset Id */
            filter_preset_id?: string | null;
            /** Process Preset Id */
            process_preset_id?: string | null;
            /** @default unknown */
            license_status: components["schemas"]["LicenseStatus"];
            /** License Note */
            license_note?: string | null;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
        };
        /** SourceChannelOut */
        SourceChannelOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            platform: components["schemas"]["SourcePlatform"];
            /** External Id */
            external_id: string;
            /** Handle */
            handle: string | null;
            /** Display Name */
            display_name: string | null;
            /** Url */
            url: string;
            /** Scan Interval Min */
            scan_interval_min: number;
            /** Last Scanned At */
            last_scanned_at: string | null;
            /** Last Seen Video Id */
            last_seen_video_id: string | null;
            /** Filter Preset Id */
            filter_preset_id: string | null;
            /** Process Preset Id */
            process_preset_id: string | null;
            license_status: components["schemas"]["LicenseStatus"];
            /** License Note */
            license_note: string | null;
            /** Enabled */
            enabled: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SourceChannelUpdate */
        SourceChannelUpdate: {
            /** Handle */
            handle?: string | null;
            /** Display Name */
            display_name?: string | null;
            /** Scan Interval Min */
            scan_interval_min?: number | null;
            /** Last Seen Video Id */
            last_seen_video_id?: string | null;
            /** Filter Preset Id */
            filter_preset_id?: string | null;
            /** Process Preset Id */
            process_preset_id?: string | null;
            license_status?: components["schemas"]["LicenseStatus"] | null;
            /** License Note */
            license_note?: string | null;
            /** Enabled */
            enabled?: boolean | null;
        };
        /**
         * SourcePlatform
         * @description Nền tảng nguồn lấy video về.
         *
         *     Ban đầu chỉ có 5 nền tảng Trung Quốc. Từ khi ô dán link nhận mọi URL
         *     http/https (yt-dlp hỗ trợ hơn 1800 site), danh sách này KHÔNG còn là cổng
         *     chặn — nó chỉ để nhận đúng ID video phục vụ chống trùng và đặt thư mục.
         *     Nguồn không nằm trong danh sách rơi vào ``OTHER`` và vẫn tải bình thường.
         * @enum {string}
         */
        SourcePlatform: "douyin" | "bilibili" | "kuaishou" | "xiaohongshu" | "weibo" | "youtube" | "tiktok" | "instagram" | "facebook" | "twitter" | "other";
        /** SubtitleCue */
        SubtitleCue: {
            /** I */
            i: number;
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Text */
            text: string;
        };
        /** SubtitleOut */
        SubtitleOut: {
            /** Lang */
            lang: string;
            /** Source */
            source: string;
            /** Edited By User */
            edited_by_user: boolean;
            /** Cues */
            cues: components["schemas"]["SubtitleCue"][];
        };
        /** TaskAccepted */
        TaskAccepted: {
            /** Task Id */
            task_id?: string | null;
            /**
             * Message
             * @default Đã đưa vào hàng đợi
             */
            message: string;
        };
        /**
         * TranslateRequest
         * @description Body của ``POST /videos/{id}/translate``.
         *
         *     ``llm_model`` bỏ trống là hợp lệ — khi đó worker dùng ``LLM_MODEL`` mặc
         *     định trong cấu hình. Không kiểm model hợp lệ ở đây mà ở tầng service:
         *     việc phân loại model là logic nghiệp vụ, không phải validate cú pháp.
         */
        TranslateRequest: {
            /** Llm Model */
            llm_model?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VideoDetail */
        VideoDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Source Platform */
            source_platform: string;
            /** Source Video Id */
            source_video_id: string;
            /** Source Url */
            source_url: string;
            /** Source Author */
            source_author?: string | null;
            /** Title Original */
            title_original?: string | null;
            /** Title Vi */
            title_vi?: string | null;
            /** Duration Sec */
            duration_sec?: number | null;
            /** Width */
            width?: number | null;
            /** Height */
            height?: number | null;
            status: components["schemas"]["VideoStatus"];
            current_step?: components["schemas"]["PipelineStep"] | null;
            /** Error Message */
            error_message?: string | null;
            /** Flags */
            flags?: {
                [key: string]: unknown;
            };
            /** Out Path */
            out_path?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Desc Original */
            desc_original?: string | null;
            /** Desc Vi */
            desc_vi?: string | null;
            /** Hashtags Vi */
            hashtags_vi?: string[] | null;
            /** Fps */
            fps?: number | null;
            /** Has Audio */
            has_audio?: boolean | null;
            /** Raw Path */
            raw_path?: string | null;
            /** Process Config */
            process_config?: {
                [key: string]: unknown;
            };
        };
        /** VideoOut */
        VideoOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Source Platform */
            source_platform: string;
            /** Source Video Id */
            source_video_id: string;
            /** Source Url */
            source_url: string;
            /** Source Author */
            source_author?: string | null;
            /** Title Original */
            title_original?: string | null;
            /** Title Vi */
            title_vi?: string | null;
            /** Duration Sec */
            duration_sec?: number | null;
            /** Width */
            width?: number | null;
            /** Height */
            height?: number | null;
            status: components["schemas"]["VideoStatus"];
            current_step?: components["schemas"]["PipelineStep"] | null;
            /** Error Message */
            error_message?: string | null;
            /** Flags */
            flags?: {
                [key: string]: unknown;
            };
            /** Out Path */
            out_path?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * VideoStatus
         * @enum {string}
         */
        VideoStatus: "queued" | "running" | "review" | "ready" | "scheduled" | "posted" | "error" | "skipped";
        /** VideoUpdate */
        VideoUpdate: {
            /** Title Vi */
            title_vi?: string | null;
            /** Desc Vi */
            desc_vi?: string | null;
            /** Hashtags Vi */
            hashtags_vi?: string[] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_videos_api_v1_videos_get: {
        parameters: {
            query?: {
                status?: string | null;
                q?: string | null;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_VideoOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    counts_api_v1_videos_counts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
        };
    };
    create_from_links_api_v1_videos_from_links_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFromLinks"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateFromLinksResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_video_api_v1_videos__video_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_video_api_v1_videos__video_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_video_api_v1_videos__video_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VideoUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_api_v1_videos__video_id__retry_post: {
        parameters: {
            query?: {
                from_step?: string | null;
            };
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    translate_api_v1_videos__video_id__translate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TranslateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_api_v1_videos__video_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_api_v1_videos_bulk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkAction"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    subtitles_api_v1_videos__video_id__subtitles_get: {
        parameters: {
            query?: {
                lang?: string | null;
            };
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubtitleOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_runs_api_v1_videos__video_id__job_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_file_api_v1_videos__video_id__file_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_presets_api_v1_presets_get: {
        parameters: {
            query?: {
                kind?: components["schemas"]["PresetKind"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_preset_api_v1_presets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresetCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_preset_api_v1_presets__preset_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                preset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresetUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_channels_api_v1_source_channels_get: {
        parameters: {
            query?: {
                platform?: components["schemas"]["SourcePlatform"] | null;
                enabled?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceChannelOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_channel_api_v1_source_channels_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceChannelCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceChannelOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_channel_api_v1_source_channels__channel_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_channel_api_v1_source_channels__channel_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channel_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceChannelUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceChannelOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_channel_api_v1_source_channels_resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveChannelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolveChannelResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_platform_limits_api_v1_platform_limits_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformLimitOut"][];
                };
            };
        };
    };
    update_platform_limit_api_v1_platform_limits__platform__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                platform: components["schemas"]["Platform"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlatformLimitUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformLimitOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    render_video_api_v1_videos__video_id__render_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_variants_api_v1_videos__video_id__variants_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenderVariantOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_variant_file_api_v1_variants__variant_id__file_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                variant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_llm_models_api_v1_llm_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmModelsOut"];
                };
            };
        };
    };
    get_llm_usage_api_v1_llm_usage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmUsageOut"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
